### ISSUE TITLE
Add base path for fontawesome sprites 

### ISSUE THREAD

**Issue by adrianfish** [obsidiansoft-io/fa-icon#1]
Make it so that we can pass in a base path for the font awesome sprites, so that the component can be used in contexts other than node. The Sakai project, where I'm using this, doesn't deploy the node_modules directory - we precompile using Empathy so we get full paths.

**Comment by QuinsZouls** [comment]
thanks for your support 🥇 . The enhancement has been merged and is available in the version 0.1.5
