### ISSUE TITLE
Component demo doesn't exist

### ISSUE THREAD

**Issue by k3llydev** [obsidiansoft-io/fa-icon#15]
Being able to clone individually the component, serve it and see something is fundamental for users to keep contributing.

The whole demo of this element is missing.

**Comment by QuinsZouls** [comment]
Thanks for the information, the demo icon is a premium icon of fontawesome, we have changed the icon to a free one to avoid confusion.

**Comment by k3llydev** [comment]
I think you misunderstood the issue. The thing is that, if you do:

```
$ polymer serve
```

Nothing is shown as a demo.

**Comment by k3llydev** [comment]
Fixed by attached pull request.
