### ISSUE TITLE
Uncaught TypeError: Failed to resolve module specifier "fa-icons"

### ISSUE THREAD

**Issue by antonioaltamura** [obsidiansoft-io/fa-icon#4]
Hello, I'm trying to use this module in a Polymer 3 project using lit-Element.

Trying your sample code I get the error

> Uncaught TypeError: Failed to resolve module specifier "fa-icons". Relative references must start with either "/", "./", or "../".

Chrome 75.0.3770.142 on Mac 10.14.5

**Comment by QuinsZouls** [comment]
Could you explain to me, what are you trying to do and how do you do it?

**Comment by QuinsZouls** [comment]
Do you use any transpilator?

**Comment by QuinsZouls** [comment]
note: in the example code premium fontawesome icons are used
