### ISSUE TITLE
Incorrect configuration for size

### ISSUE THREAD

**Issue by amimas** [obsidiansoft-io/fa-icon#5]
The documentation and the sample code says the `size` parameter is `String` but it seems to be `Number` in the source code (line 11):

https://github.com/obsidiansoft-io/fa-icon/blob/880a8a2c7ac677cd7e5d2d27bb0d75607f62e2aa/fa-icon.js#L5-L14

If I set the `size` parameter as `Number` it doesn't seem to work for me. If I set it as `String` as shown in the readme file of this repo, it works but my editor (visual studio code) complains that I have a syntax error (passing `String` instead of `Number` in the parameter value).

**Comment by QuinsZouls** [comment]
Thanks for report, now size is type String in the version 0.1.6.

**Comment by amimas** [comment]
Cool!! I'll try it out soon. Thanks for the quick fix.

**Comment by QuinsZouls** [comment]
maybe the eslint you use detects the word "size" by default as if it were a numeric type

**Comment by amimas** [comment]
I have the following ESLint installed and enabled, but don't have any `.eslintrc` file or any rules configured in the `settings.json` of that linter.

I think there's still issue in the code. Just realized that the latest version is still setting the `size` as a number in the constructor instead of a string.

https://github.com/obsidiansoft-io/fa-icon/blob/af87472d5332cc89c7e052002c867deaa8a252a8/fa-icon.js#L44-L52

If I manually update the source in my node modules and set that value as a string in the constructor, I don't see anymore errors on my element (although I see other linter errors on your source about missing semi-colon)

**Comment by amimas** [comment]
Can this issue be reopened please?

**Comment by QuinsZouls** [comment]
Thanks for report, now size is type String in the constructor, fixed in the version 0.1.7
I will leave the issue open until you have verified that the change really worked

**Comment by amimas** [comment]
Yup. It seems to be fixed now. Thanks!!
